# Site settings
title: Juan Roa
description: 'Full stack Web Developer from Cali, Colombia. Ruby on Rails | SASS | PostgreSQL | Linux SysAdmin'
url: 'http://juanroa.me'
baseurl: '/'
google_analytics: 'UA-72523770-1'
language: 'es'
disqus_shortname: 'juanroa'

author:
  name: 'Juan Roa'
  email: jdroa92@gmail.com
  twitter_username: jroadev
  github_username:  roadev
  linkedin_username:  roadev

# Build settings
destination: _site
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page:num"
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _scss
  style: :compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
